president@mydomain.org
collard@gmail.com
You were nominated for the board election
<p>Hi Lynn, you were nominated for Board Member in the upcoming elections.</p>
<p></p>
<p>From the 2 members who submitted nominations, you received 1 nomination(s) out of 4.</p>
<p></p>
<p>You can accept or decline your nomination by filling out this short <a href='Form URL'> Nomination Response Form </a>.</p>
<p></p>
<p>Please respond now if at all possible, or within 3 days so the members can have a week to consider the nominees.</p>
<p></p>
<p>Thank you,</p>
<p></p>
<p>The Board</p>
